djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, LogoutView,
    )
from django.urls import path, include
from leads.views import LandingPageView, SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing_page'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('signup/', SignUpView.as_view(), name='sign_up'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from leads import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='lead_list'),
    path('create/', views.LeadCreateView.as_view(), name='lead_create'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='lead_detail'),
    path('<int:pk>/update/', views.LeadUpdtaeView.as_view(), name='lead_update'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='lead_delete'),
]

agents/models.py
from django.db import models

# Create your models here.

leads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class User(AbstractUser):
    pass


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    agent = models.ForeignKey('Agent', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('leads:lead_detail', args=[self.pk])

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


def post_user_created_signal(sender, instance, created, **kwargs):
    print(instance, created)
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(post_user_created_signal, sender=User)

leads/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import Lead


User = get_user_model()


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent',
        )


class LeadForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    age = forms.IntegerField(min_value=0)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = {'username'}
        field_classes = {'username': UsernameField}

agents/views.py
from django.shortcuts import render

# Create your views here.

leads/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView, CreateView
)
from django.urls import reverse
from .models import Lead, Agent
from .forms import LeadModelForm, LeadForm, CustomUserCreationForm


class SignUpView(CreateView):
    template_name = 'registration/sign_up.html'
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse('login')


class LandingPageView(TemplateView):
    template_name = 'landing_page.html'


class LeadListView(LoginRequiredMixin,ListView):
    template_name = 'leads/lead_list.html'
    queryset = Lead.objects.all()
    context_object_name = 'leads'


class LeadDetailView(LoginRequiredMixin,DetailView):
    template_name = 'leads/lead_detail.html'
    model = Lead
    context_object_name = 'lead'


class LeadCreateView(LoginRequiredMixin,CreateView):
    template_name = 'leads/lead_create.html'
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse('leads:lead_list')

    def form_valid(self, form):
        send_mail(
            subject='A lead has been created',
            message='Go to the site to check it out',
            from_email='test@testUser.com',
            recipient_list=['test@testAdmin.com'],
            fail_silently=False
        )
        return super().form_valid(form)


class LeadUpdtaeView(LoginRequiredMixin,UpdateView):
    template_name = 'leads/lead_update.html'
    form_class = LeadModelForm
    model = Lead


class LeadDeleteView(LoginRequiredMixin,DeleteView):
    template_name = 'leads/lead_delete.html'
    model = Lead

    def get_success_url(self):
        return reverse('leads:lead_list')

leads/templates/leads/lead_create.html
{% extends "base.html" %}
{% block content %}
<a href="{% url 'leads:lead_list' %}">Go back</a>
<h1>
    Create Lead
</h1>
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

leads/templates/leads/lead_delete.html
{% extends "base.html" %}
{% block content %}
<a href="{% url 'leads:lead_list' %}">Go back</a>
<h1>
    Are you sure you want to delete this lead?
</h1>
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

leads/templates/leads/lead_detail.html
{% extends "base.html" %}
{% block content %}
<h1>
    Lead Detail
</h1>
<a href="{% url 'leads:lead_list' %}">Go back</a> 
<p>
    👨  Agent for the lead is {{ lead.agent }}
</p>
<p>
    {{ lead }}, {{ lead.age }}
</p>
<a href="{% url 'leads:lead_update' lead.pk %}"> Update lead</a> or <a href="{% url 'leads:lead_delete' lead.pk %}">Delete lead</a>
{% endblock %}

leads/templates/leads/lead_list.html
{% extends "base.html" %}
{% block content %}
<a href="{% url 'leads:lead_create' %}">Create New Lead</a>
<h1>
    All the leads listed
</h1>
<ul>
    {% for lead in leads %}
    <li> <a href="{% url 'leads:lead_detail' lead.pk %}"> {{ lead.first_name }} {{ lead.last_name }} </a> , {{ lead.age }}</li>
    {% endfor %}
</ul>
{% endblock %}

leads/templates/leads/lead_update.html
{% extends "base.html" %}
{% block content %}
<a href="{% url 'leads:lead_list' %}">Go back</a>
<h1>
    Update Lead: {{ lead.first_name }} {{ lead.last_name }}
</h1>
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    {% include 'navbar.html' %}
    <a href="{% url 'landing_page' %}">DjCRM Home</a>
    {% block content %}
    {% endblock %}
    <!-- <script src="{% static 'js/main.js' %}"></script> -->
</body>

</html>

templates/landing_page.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome to Django CRM</h1>
    <a href="{% url 'leads:lead_list' %}">View Leads</a>
{% endblock content %}

templates/navbar.html
<header>
    <span>Navbar goes here: </span>
    {% if request.user.is_authenticated %}
        <span>Logged-In as {{ request.user.username }}</span>
        <a href="{% url 'logout' %}">Log-Out 🔻 </a>
    {% else %}
    <a href="{% url 'login' %}">Log-In 👉 </a>
    <span> or </span>
    <a href="{% url 'sign_up' %}">Sign-Up 📲    </a>
    {% endif %}
</header>